# Generated by Django 5.2 on 2025-08-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_hashtag_post_hashtags_follow_savedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
    ]
