# Generated by Django 5.2.1 on 2025-08-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
