# Generated by Django 5.2.3 on 2025-06-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("spoonacular_id", models.IntegerField(unique=True)),
            ],
        ),
    ]
