# Generated by Django 5.2.3 on 2025-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_spoonacular_id_alter_recipe_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrecipeinteraction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "User Recipe Interaction",
                "verbose_name_plural": "User Recipe Interactions",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True),
        ),
    ]
