# Generated by Django 5.2.3 on 2025-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_userrecipeinteraction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
