# Generated by Django 5.2.3 on 2025-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.TextField(blank=True),
        ),
    ]
