# Generated by Django 5.2.1 on 2025-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
