# Generated by Django 5.2.1 on 2025-08-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipe_calories_recipe_carbs_recipe_fat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTastePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dietary_preferences",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("keto", "Keto"),
                            ("gluten-free", "Gluten-Free"),
                            ("vegan", "Vegan"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "allergies",
                    models.CharField(
                        choices=[
                            ("lactose", "Lactose Intolerance"),
                            ("nut", "Nut Allergy"),
                            ("gluten", "Gluten Intolerance"),
                            ("shellfish", "Shellfish Allergy"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("disliked_ingredients", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
