# Generated by Django 5.2.1 on 2025-08-09 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_usertastepreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertastepreference",
            name="dietary_preferences",
        ),
        migrations.RemoveField(
            model_name="usertastepreference",
            name="disliked_ingredients",
        ),
        migrations.AddField(
            model_name="usertastepreference",
            name="diet",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usertastepreference",
            name="dislikes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usertastepreference",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usertastepreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
