# Generated by Django 5.2.1 on 2025-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_usertastepreference_dietary_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrecipeinteraction",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="userrecipeinteraction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usertastepreference",
            name="diet",
        ),
        migrations.AddField(
            model_name="usertastepreference",
            name="dietary_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="spoonacular_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="UserRecipeInteraction",
        ),
    ]
