# Generated by Django 5.2.1 on 2025-08-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_remove_userrecipeinteraction_recipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertastepreference",
            name="dislikes",
        ),
    ]
