<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-07-19 14:51
=======
# Generated by Django 5.2 on 2025-05-01 17:04
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('spoonacular_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile image (jpg, jpeg, png, or gif)', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('dietary_preference', models.TextField(blank=True, help_text="User's dietary preferences (comma-separated)", null=True)),
                ('allergies', models.TextField(blank=True, help_text="List of user's allergies", null=True)),
                ('dislikes', models.TextField(blank=True, help_text='List of foods user dislikes', null=True)),
                ('has_completed_questions', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='user_favorites', to='recipes.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='UserRecipeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('save', 'Saved'), ('rate', 'Rated')], max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe', 'interaction_type')},
            },
        ),
=======
>>>>>>> main
    ]
