# Generated by Django 5.2.1 on 2025-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_questions',
            field=models.BooleanField(default=False),
        ),
    ]
