# Generated by Django 5.2.1 on 2025-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userprofile_has_completed_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-last_updated'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text="List of user's allergies", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten-free', 'Gluten Free'), ('dairy-free', 'Dairy Free'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('none', 'No Specific Plan')], help_text="User's dietary preference", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dislikes',
            field=models.TextField(blank=True, help_text='List of foods user dislikes', null=True),
        ),
    ]
