# Generated by Django 5.2.1 on 2025-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_userprofile_options_userprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.TextField(blank=True, help_text="User's dietary preferences (comma-separated)", null=True),
        ),
    ]
