# Generated by Django 5.2.1 on 2025-06-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_userprofile_allergies_userprofile_dietary_preference_and_more'),
        ('recipes', '0004_contactmessage'),
    ]

    operations = [
    ]
