# Generated by Django 5.2.1 on 2025-08-12 12:54

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code_created_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), recipes.models.validate_image_size]),
        ),
    ]
