# Generated by Django 5.2.1 on 2025-08-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_customuser_profile_picture'),
        ('recipes', '0022_alter_customuser_profile_picture'),
    ]

    operations = [
    ]
